<#
.SYNOPSIS
Syntactic sugar for inline if/else (ternary operator).

.DESCRIPTION
Syntactic sugar for inline if/else (ternary operator).

.PARAMETER if
Boolean statement to be evaluated

.PARAMETER right
Argument that will be used if evaluation was true

.PARAMETER wrong
Argument that will be used if evaluation was false

.EXAMPLE
(IIf (1 -eq (2-1)) "statement is true" "statement is false")

#>
Function IIf([bool] $if, $right, $wrong) {
    If ($if) {$right} Else {$wrong}
}


<#
.SYNOPSIS
Method to generate value for basic authentication header in, e.g., Invoke-RestMethod Cmdlet. 

.DESCRIPTION
Method to generate value for basic authentication header in, e.g., Invoke-RestMethod Cmdlet.

.PARAMETER username
User name

.PARAMETER password
Password

.EXAMPLE
Invoke-RestMethod -Uri "www.example.org" -Method Get -Headers @{Authorization=("Basic {0}" -f (CreateBasicAuthHeader "admin" "12345678"))} 

#>
function CreateBasicAuthHeader([string] $username, [string] $password) {
    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username, $password)))
    return $base64AuthInfo
}

<#
.SYNOPSIS
Method to call web resource.

.DESCRIPTION
Method to call web resource.

.PARAMETER url
Resource url

.PARAMETER right
HTTP method to be used (Microsoft.PowerShell.Commands.WebRequestMethod), specified as a string, e.g. Get, Post, Put

.PARAMETER auth
String generated by CreateBasicAuthHeader Cmdlet

.EXAMPLE
(CallResource "example.org" Get "k23h56k34j6n623k46h")

#>
Function CallResource ([string] $url, [string] $method, [string] $auth) {
    Write-Host "Calling resource '$url'"
    $data = Invoke-RestMethod -Uri $url -Method $method -Headers @{Authorization=("Basic {0}" -f $auth)}
    return $data
}